package model

import "time"

const ZeroCreds = "zeroCreds"

type User struct {
	DeletedAt time.Time `json:"deleted_at" pg:",soft_delete"`
	CreatedAt time.Time `json:"created_at"`
	Username  string    `json:"username" binding:"required" pg:",unique"`
	Email     string    `json:"email" binding:"required" pg:",unique"`
	Password  string    `json:"password" binding:"required"`
	ID        int64     `json:"id" pg:",pk"`
	RoleID    uint      `json:"role_id"`
}

type UserRequest struct {
	Username string `json:"username" binding:"required"`
	Email    string `json:"email" binding:"required"`
	Password string `json:"password" binding:"required"`
	RoleID   uint   `bson:"role_id" json:"role_id"`
}

type GoogleUser struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	GivenName     string `json:"given_name"`
	FamilyName    string `json:"family_name"`
	Picture       string `json:"picture"`
	VerifiedEmail bool   `json:"verified_email"`
}

type GithubUser struct {
	Email         string `json:"email"`
	Name          string `json:"name"`
	GivenName     string `json:"given_name"`
	FamilyName    string `json:"family_name"`
	Picture       string `json:"picture"`
	ID            int    `json:"id"`
	VerifiedEmail bool   `json:"verified_email"`
}

type UserFindOpts struct {
	Username Filter
	Email    Filter
	RoleID   Filter
	FieldsOpts
	PaginationOpts
}

type AutoGenerated struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Type      string `json:"type"`
	Company   string `json:"company"`
	Login     string `json:"login"`
	ID        int    `json:"id"`
	SiteAdmin bool   `json:"site_admin"`
}
