apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"test1","namespace":"default"},"spec":{"containers":[{"image":"redis","name":"container1"}]}}
  creationTimestamp: "2024-09-03T08:42:44Z"
  name: test1
  namespace: default
  resourceVersion: "2573"
  uid: 78392cd4-60dd-4604-a6e6-64580432c07a
spec:
  containers:
    - image: redis
      imagePullPolicy: Always
      name: container1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-rrfm5
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: orbstack
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-rrfm5
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-09-03T08:42:51Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2024-09-03T08:42:44Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-09-03T08:42:51Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-09-03T08:42:51Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-09-03T08:42:44Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://213464a75d25bc90c15e5b64a10b113840998b4eab211c5a595a91f3dba21325
      image: redis:latest
      imageID: docker-pullable://redis@sha256:878983f8f5045b28384fc300268cec62bca3b14d5e1a448bec21f28cfcc7bf78
      lastState: {}
      name: container1
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-09-03T08:42:50Z"
  hostIP: 198.19.249.2
  hostIPs:
    - ip: 198.19.249.2
    - ip: fd07:b51a:cc66::2
  phase: Running
  podIP: 192.168.194.7
  podIPs:
    - ip: 192.168.194.7
    - ip: fd07:b51a:cc66:a::7
  qosClass: BestEffort
  startTime: "2024-09-03T08:42:44Z"
