version: "3.9" # Docker Compose version

services:
  app:
    build: .
    # image: kubernetes-api:latest  # Docker image for your Go application
    container_name: app-container
    environment:
      - KUBECONFIG=/root/.kube/config # Location of the Kubernetes configuration file
    volumes:
      - ~/.kube/config:/root/.kube/config # Mount the local kubeconfig file to the container
    ports:
      - "8080:8080" # Expose necessary ports
    networks:
      - mynetwork
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kubernetes-api
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge # Use bridge network to enable communication between services
