apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api-app
  namespace: default
spec:
  replicas: 2 # this is number of pods
  selector:
    matchLabels:
      app: kubernetes-api-app
  template:
    metadata:
      labels:
        app: kubernetes-api-app
    spec:
      # Kubernetes run docker pull pseudo/your-image:latest under the hood
      # Image field in Kubernetes resources is simply the docker image to run.
      containers:
        - name: kubernetes-api-app
          # pulling image from my DockerHub
          image: 1149/kubernetes-api:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
              cpu: "250m"
            requests:
              memory: 32Mi
              cpu: "200m"
          # specify the container port
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube/config
              subPath: config
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-app-entrypoint
  namespace: default
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: kubernetes-api-app
  # The range of valid ports in kubernetes is 30000-32767
  ports:
    - name: http
      protocol: TCP
      port: 8080 # this is service port 80
      targetPort: 8080
      # nodePort: 30003      # this is for when using type: NodePort
    - name: https
      protocol: TCP
      port: 443 # this is service port 443
      targetPort: 30002
      # nodePort: 30004      # this is for when using type: NodePort
