apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full-access-clusterrole
  namespace: kubernetes-api-namespace
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "deployments"]
    verbs: ["create", "get", "list", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-clusterbinding
  namespace: kubernetes-api-namespace
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubernetes-api-namespace
roleRef:
  kind: ClusterRole
  name: full-access-clusterrole
  apiGroup: rbac.authorization.k8s.io
