apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: kubernetes-api-namespace
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: 1149/kubernetes-api:latest
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          ports:
            - containerPort: 8080
      volumes:
        - name: config-volume
          configMap:
            name: app-config-map

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: kubernetes-api-namespace
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
